include:
  - project: "repos/cloud/cicd/gitlab-ci"
    file: "py3.11-bookworm-tox/gitlab-ci.yaml"
  - project: "repos/cloud/cicd/gitlab-ci"
    file: "toolforge-cd/only_image_publish.yaml"
  - project: "repos/cloud/cicd/gitlab-ci"
    file: "toolforge-cd/only_helm_publish.yaml"


# T397949: testing new linter setup
lint-docs:
  stage: test
  image:
    name: jdkato/vale:latest
    entrypoint: [""]

  variables:
    VALE_CONFIG_PATH: .vale.ini
    VALE_FILES_PATH: README.md

  script:
    - vale --config=$VALE_CONFIG_PATH sync
    - vale --config=$VALE_CONFIG_PATH $VALE_FILES_PATH


variables:
  PROJECT_NAME: components-api
